const A="assets/";let S=JSON.parse(localStorage.getItem("bc4")||'{"happy":78,"energy":70,"hungry":58,"ready":64,"outfit":0,"fed":""}');
const save=()=>localStorage.setItem("bc4",JSON.stringify(S));const app=document.querySelector("#app");
function nav(){return `<nav class="bottom"><button onclick="go('home')"><b>⌂</b>Ana Sayfa</button><button onclick="go('food')"><b>♨</b>Yemek</button><button onclick="go('costume')"><b>♧</b>Kostüm</button><button onclick="go('concert')"><b>♫</b>Konser</button><button onclick="go('more')"><b>•••</b>Daha Fazla</button></nav>`}
function top(t){return `<header><button class="back" onclick="history.back()">‹</button><h1>${t}</h1><button class="menu" onclick="go('more')">☰</button></header>`}
function shell(t,b){app.innerHTML=`<main class="screen">${top(t)}${b}</main>${nav()}`}
function go(p){history.pushState({p},"","#"+p);render(p)}
function toast(t){let d=document.createElement("div");d.className="toast";d.textContent=t;document.body.append(d);setTimeout(()=>d.remove(),1600)}
function stats(){return `<div class="stats">${[['♥ Mutluluk',S.happy],['⚡ Enerji',S.energy],['🍴 Açlık',S.hungry],['★ Konser Hazır',S.ready]].map(x=>`<div class="stat"><span>${x[0]}</span><div class="bar"><i style="width:${x[1]}%"></i></div><small>${x[1]}</small></div>`).join("")}</div>`}
function render(p=location.hash.slice(1)||"start"){
if(p==="start"){app.innerHTML=`<main class="screen"><div class="logo">BETONCHI</div><div class="tag">Adopt his day ♡</div><img class="char" src="${A}hero.webp"><div class="bubble">Music · Food · Outfits · Concert and more…</div><button class="primary" onclick="go('welcome')">BAŞLA →</button></main>`;return}
if(p==="welcome"){app.innerHTML=`<main class="screen"><div class="logo">Hoş Geldin!</div><img class="char" src="${A}hero.webp"><div class="bubble">Artık sen de BETONCHI dünyasındasın!<br>Bugün Beton’un günü, birlikte yaşayalım. ♡</div><button class="primary" onclick="go('home')">HAYDİ! →</button></main>`;return}
if(p==="home"){shell("BETONCHI",`<div class="bubble">Bugün harika bir gün! ♡</div><img class="char" src="${A}hero.webp">${stats()}`);return}
if(p==="food"){let foods=[['🍔','Burger'],['🍜','Noodle'],['☕','Kahve'],['🍕','Pizza'],['🍲','Çorba'],['🍰','Tatlı']];shell("Yemek Zamanı",`<img class="char" src="${A}foodchar.webp"><div class="bubble">${S.fed?`Beton ${S.fed} yedi! ♡`:'Beton acıktı! Ne yedirelim? ♡'}</div><div class="foodgrid">${foods.map((x,i)=>`<button class="food ${S.fed===x[1]?'selected':''}" onclick="feed('${x[1]}')"><b>${x[0]}</b>${x[1]}</button>`).join("")}</div><button class="primary" onclick="eat()">YEDİR →</button>`);return}
if(p==="costume"){let looks=['🧥','🤍','🟥','🖤'];shell("Kostüm",`<img id="costumeChar" class="char" src="${A}costume.webp"><div class="costumes">${looks.map((x,i)=>`<button class="look ${S.outfit===i?'selected':''}" onclick="outfit(${i})">${x}</button>`).join("")}</div><div class="bubble" id="lookText">${['Yeşil sahne ceketi','Beyaz özel kostüm','Kırmızı konser kostümü','Siyah gece kostümü'][S.outfit]}</div><button class="primary" onclick="toast('Kostüm kaydedildi ♡')">BU KOSTÜMÜ SEÇ →</button>`);return}
if(p==="concert"){shell("Konser Modu",`<div class="stage"><img class="char" src="${A}concert.webp"><div>Beton sahnede! ♡</div></div>${stats()}<button class="primary" onclick="concert()">LET’S GO! →</button>`);return}
if(p==="diary"){shell("Günlük",`<div class="timeline"><div class="event"><b>08:00</b><br>Beton uyandı — Günaydın! ♡</div><div class="event"><b>12:00</b><br>Beton yemek yedi — Enerjisi yükseldi!</div><div class="event"><b>15:00</b><br>Prova zamanı — Çok çalışıyor! ♡</div><div class="event"><b>19:00</b><br>Kostümünü değiştirdi — Sahneye hazır!</div><div class="event"><b>21:00</b><br>KONSER — Efsaneydi! ♡</div></div>`);return}
if(p==="game"){shell("Mini Oyun",`<div class="card" style="text-align:center"><img class="char" src="${A}hero.webp"><h2>Beton’a yardım et!</h2><p>Yıldızları topla, konser alanına ulaş!</p><button class="primary" onclick="star()">★ YILDIZ TOPLA</button></div>`);return}
if(p==="album"){shell("Fotoğraf Albümü",`<div class="album"><img src="${A}hero.webp"><img src="${A}concert.webp"><img src="${A}message.webp"><img src="${A}costume.webp"></div>`);return}
if(p==="message"){shell("Özel Mesaj",`<img class="char" src="${A}message.webp"><div class="bubble">Bugün sizinle çok eğlendim.<br>İyi ki varsınız. ♡</div><button class="primary" onclick="toast('Mesaj saklandı ♡')">MESAJI SAKLA →</button>`);return}
if(p==="notifications"){shell("Bildirimler",`<div class="card">Beton seni özledi…<br><small>2 saat önce</small></div><div class="card">Beton kostüm seçiyor!<br><small>Bugün 15:00</small></div><div class="card">Beton yemek zamanı!<br><small>Bugün 12:00</small></div><div class="card">Beton sahneye çıkıyor!<br><small>Bugün 20:00</small></div>`);return}
shell("Ayarlar & Diğer",`<div class="moregrid"><button class="tile" onclick="go('diary')"><b>♡</b>Günlük</button><button class="tile" onclick="go('game')"><b>★</b>Mini Oyun</button><button class="tile" onclick="go('album')"><b>▣</b>Albüm</button><button class="tile" onclick="go('message')"><b>✉</b>Özel Mesaj</button><button class="tile" onclick="go('notifications')"><b>♧</b>Bildirimler</button><button class="tile" onclick="toast('BETONCHI ♡')"><b>ⓘ</b>Hakkında</button></div>`)
}
let chosen="";function feed(x){chosen=x;document.querySelectorAll(".food").forEach(b=>b.classList.toggle("selected",b.textContent.includes(x)));toast(x+" seçildi")}
function eat(){if(!chosen){toast("Önce bir yemek seç ♡");return}S.fed=chosen;S.hungry=Math.max(0,S.hungry-18);S.energy=Math.min(100,S.energy+9);S.happy=Math.min(100,S.happy+5);save();render("food");toast("Beton gerçekten yedi! ♡")}
function outfit(i){S.outfit=i;S.happy=Math.min(100,S.happy+2);save();render("costume");toast("Kostüm değişti!")}
function concert(){S.ready=Math.min(100,S.ready+12);S.energy=Math.max(0,S.energy-8);S.happy=Math.min(100,S.happy+8);save();render("concert");toast("Konser başladı! ★")}
function star(){S.ready=Math.min(100,S.ready+4);S.happy=Math.min(100,S.happy+3);save();toast("★ Yıldız topladın!")}
window.onpopstate=()=>render();render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");